/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBaseCollection } from "./IBaseCollection";
export type { IDropKitPass } from "./IDropKitPass";
export type { INiftyKit } from "./INiftyKit";
